"""Generate maintained interaction and picker documentation from the UI catalogue."""
import argparse
from pathlib import Path
import sys

ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'src'))
from thermodraw._catalogue import catalogue

def build():
    c=catalogue()
    lines=['# Interaction and notation catalogue', '',
           'Generated by `python tools/gen_editor_guide.py`. Edit `_catalogue.py` or `_units.py`, then regenerate.', '',
           '| Item | Meaning and appearance | Action | Changes | Cancel or undo |',
           '|---|---|---|---|---|']
    for e in c['interactions']:
        lines.append('| '+' | '.join(e[k] for k in ('name','when','action','changes','cancel'))+' |')
    lines+=['','## Inspector controls','','| Control | Explanation |','|---|---|']
    lines+=['| '+key+' | '+value+' |' for key,value in c['controls'].items()]
    lines+=['','## Prefixes','','Reference: [BIPM SI prefix catalogue](https://www.bipm.org/en/measurement-units/si-prefixes).',
            'Select a unit token to replace its prefix; mass prefixes attach to grams. Undo restores insertion.',
            '','| Symbol | Name | Scale |','|---|---|---|']
    lines+=['| '+(e['symbol'] or '(none)')+' | '+e['name']+' | 10^'+str(e['exponent'])+' |' for e in c['prefixes']]
    lines+=['','## Unit presets','','Each preset is filtered by quantity. Typed compatible prefixes and compound expressions are also accepted.',
            '','| Quantity | Supported presets |','|---|---|']
    lines+=['| '+q+' | '+', '.join(units)+' |' for q,units in c['presets'].items()]
    lines+=['','## Scientific symbols','','Insert at the caret or replace the selection in labels and subscripts. These tokens change notation only; Undo restores text.',
            'Numeric and integer fields expose only applicable numeric shortcuts. Text is escaped and never executed.',
            '','| Symbol | Common name |','|---|---|']
    lines+=['| '+e['symbol']+' | '+e['name']+' |' for e in c['symbols']]
    return '\n'.join(lines)+'\n'

if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    path=ROOT/'docs/editor-interactions.md';fresh=build()
    if args.check:
        if not path.exists() or path.read_text(encoding='utf-8')!=fresh:
            raise SystemExit('Editor interaction guide is stale; run tools/gen_editor_guide.py')
    else:path.write_text(fresh,encoding='utf-8',newline='\n')
