"""Generate the character width tables from the real fonts.

    python tools/gen_metrics.py <dir-of-ttfs> [-o src/thermodraw/_metrics.py]

The label solver clears text by width, and it was clearing against a table of
sixteen hand-written entries with 0.55 assumed for everything else — 36 of the
52 glyphs the library actually emits. Measured against IBM Plex, the mean
per-glyph error was 12%, and 98% for "/".

Widths are advances over units-per-em, so they multiply straight by the font
size the way core.text_w already expects. Kerning is deliberately ignored:
text_w sums advances and cannot see a kern pair, and the vendored subset drops
GPOS for the same reason, so the model and the render agree.
"""
import argparse
import pathlib

from fontTools.ttLib import TTFont

FACES = {"regular": "IBMPlexSans-Regular.ttf",
         "italic": "IBMPlexSans-Italic.ttf",
         "semibold": "IBMPlexSans-SemiBold.ttf"}

# Printable ASCII, Latin-1, and the characters the symbol set reaches for.
EXTRA = "\u00b0\u2192\u2033\u00b2\u00b3\u00d7\u00b1\u2212\u2013\u2014\u2034\u00b7\u0394\u0398\u03a9\u03bb\u03bc\u2018\u2019\u201c\u201d\u2026"
CHARS = ([chr(c) for c in range(32, 127)]
         + [chr(c) for c in range(160, 256)] + list(EXTRA))

HEADER = '''"""Character advance widths, as a fraction of the font size.

Generated by tools/gen_metrics.py from {family}. Do not edit by hand.

One table per face: SemiBold runs about 4% wider than Regular, which is the
same size as the error a measured table exists to remove. FALLBACK is the mean
advance for that face, used for a character the table does not carry.

Regenerate with:

    python tools/gen_metrics.py <dir-of-ttfs>
"""
FAMILY = {family!r}
'''


def widths(font):
    upem = font["head"].unitsPerEm
    cmap = font.getBestCmap()
    hmtx = font["hmtx"]
    out = {}
    for ch in CHARS:
        glyph = cmap.get(ord(ch))
        if glyph is None or glyph not in hmtx.metrics:
            continue
        out[ch] = round(hmtx[glyph][0] / upem, 4)
    return out


def family_name(font):
    for rec in font["name"].names:
        if rec.nameID == 1:
            return str(rec)
    return "unknown"


def render(family, tables):
    nl = chr(10)
    fallback = {f: round(sum(t.values()) / len(t), 4) for f, t in tables.items()}
    out = [HEADER.format(family=family), nl, f"FALLBACK = {fallback!r}", nl, nl,
           "WIDTHS = {", nl]
    for face, table in tables.items():
        out.append(f'    "{face}": {{{nl}')
        for ch, w in sorted(table.items()):
            out.append(f"        {ch!r}: {w},{nl}")
        out.append(f"    }},{nl}")
    out.append("}" + nl)
    return "".join(out)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("src", type=pathlib.Path, help="directory holding the TTFs")
    ap.add_argument("-o", "--out", type=pathlib.Path,
                    default=pathlib.Path("src/thermodraw/_metrics.py"))
    args = ap.parse_args(argv)

    tables, family = {}, "unknown"
    for face, name in FACES.items():
        path = args.src / name
        if not path.exists():
            raise SystemExit(f"missing {path}")
        font = TTFont(path)
        tables[face] = widths(font)
        if face == "regular":
            family = family_name(font)

    with open(args.out, "w", encoding="utf-8", newline=chr(10)) as f:
        f.write(render(family, tables))
    counts = ", ".join(f"{k} {len(v)}" for k, v in tables.items())
    print(f"{family}: {counts} glyphs -> {args.out}")


if __name__ == "__main__":
    main()
